#!/bin/bash
echo "$*" >> "$HOME/gh.calls"
case "$1 $2" in
  "auth status") exit "${FAKE_CLI_AUTH_EXIT:-0}" ;;
  "pr list") grep -c "pr create" "$HOME/gh.calls" ;;
  "pr create") echo https://github.com/acme/brewfiles/pull/1 ;;
esac
